# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus.home']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['beelink.home:9100']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana.home']

  - job_name: 'snmp_exporter'
    static_configs:
    - targets: ['beelink.home:9116']

  - job_name: 'coredns'
    static_configs:
      - targets: ['beelink.home:9153']

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['bb-beelink.home:9115']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.7.88  # SNMP device.
    metrics_path: /snmp
    params:
      module: [zyxel]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: beelink.home:9116  # The SNMP exporter's real hostname:port.

  - job_name: 'blackbox_external_dns'
    metrics_path: /probe
    params:
      module: [dns_google_a]
    static_configs:
      - targets:
        - 8.8.4.4  # Test various public DNS providers are working.
        - 8.8.8.8
        - 1.0.0.1
        - 1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://google.com   # Target to probe with https.
        - http://grafana.home/api/health
        - http://prometheus.home/-/healthy
        - http://beelink.home:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox_internal_dns'
    metrics_path: /probe
    params:
      module: [dns_home_a, dns_google_a]
    static_configs:
      - targets:
        - 192.168.7.86
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
