# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

remote_write:
  - url: http://cortex.home:9009/api/prom/push

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus.home']

  - job_name: 'cortex'
    static_configs:
    - targets: ['cortex.home:9009']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['beelink.home:9100', 'pi1.home:9100', 'pi2.home:9100', 'ryzen1.home:9100', 'devbox1.home:9100', 'kube-cp1.home:9100']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana.home']

  - job_name: 'snmp_exporter'
    static_configs:
    - targets: ['beelink.home:9116']

  - job_name: 'coredns'
    static_configs:
      - targets: ['beelink.home:9153']

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['bb-beelink.home:9115']

  - job_name: 'snmp'
    scrape_interval: 60s
    static_configs:
      - targets:
        - 192.168.7.88  # SNMP device.
    metrics_path: /snmp
    params:
      module: [zyxel]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: beelink.home:9116  # The SNMP exporter's real hostname:port.

  - job_name: 'blackbox_external_dns'
    metrics_path: /probe
    params:
      module: [dns_google_a]
    file_sd_configs:
      - files:
        - '/etc/__blackbox__dns_google_a__targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: job
        replacement: 'blackbox_external_dns'
      - target_label: module
        replacement: 'dns_google_a'
      - source_labels: [exporter]
        target_label: __address__

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - '/etc/__blackbox__http_2xx__targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: job
        replacement: 'blackbox'
      - target_label: module
        replacement: 'http_2xx'
      - source_labels: [exporter]
        target_label: __address__

  - job_name: 'blackbox_internal_dns'
    metrics_path: /probe
    params:
      module: [dns_home_a, dns_google_a]
    file_sd_configs:
      - files:
        - '/etc/__blackbox__dns_home_a__targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: job
        replacement: 'blackbox_internal_dns'
      - target_label: module
        replacement: 'dns_home_a,dns_google_a'
      - source_labels: [exporter]
        target_label: __address__
